#ifndef _DATAPACKET_M_H_
#define _DATAPACKET_M_H_

#include <omnetpp.h>
#include "ApplicationPacket_m.h"

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif


void doPacking(cCommBuffer *b, AppNetInfoExchange_type& a);
void doUnpacking(cCommBuffer *b, AppNetInfoExchange_type& a);

/**
 * Class generated from <tt>src/node/application/DataPacket.msg:33</tt> by nedtool.
 * <pre>
 * packet DataPacket
 * {
 *     AppNetInfoExchange_type appNetInfoExchange;
 * 
 *     string applicationID;		// virtual app uses application ID to filter packet delivery.
 *     unsigned int sequenceNumber;// a field to distinguish between packets
 *     double data;				// a simple type to carry some data
 * }
 * </pre>
 */
class DataPacket : public ::cPacket
{
  protected:
    AppNetInfoExchange_type appNetInfoExchange_var;
    opp_string applicationID_var;
    unsigned int sequenceNumber_var;
	double* data_packet;

  private:
    void copy(const DataPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DataPacket&);

  public:
    DataPacket(const char *name=NULL, int kind=0);
    DataPacket(const DataPacket& other);
    virtual ~DataPacket();
    DataPacket& operator=(const DataPacket& other);
    virtual DataPacket *dup() const {return new DataPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual AppNetInfoExchange_type& getAppNetInfoExchange();
    virtual const AppNetInfoExchange_type& getAppNetInfoExchange() const {return const_cast<DataPacket*>(this)->getAppNetInfoExchange();}
    virtual void setAppNetInfoExchange(const AppNetInfoExchange_type& appNetInfoExchange);
    virtual const char * getApplicationID() const;
    virtual void setApplicationID(const char * applicationID);
    virtual unsigned int getSequenceNumber() const;
    virtual void setSequenceNumber(unsigned int sequenceNumber);
	virtual double* getDataPacket() const;
    virtual void setDataPacket(double* data);
	
};

inline void doPacking(cCommBuffer *b, DataPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DataPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _DATAPACKET_M_H_

